### ISSUE TITLE
[Help] Installation of ICP using vagrant failed, possibly due to timeout error

### ISSUE THREAD

**Issue by onzihao** [IBM/deploy-ibm-cloud-private#208]
Hi, I think my installation failed, possibly due to the following timeout error, as after the ansible script has completed, there was some SSH issues . Would like to know, whether is it possible to change the timeout from 60 seconds to 3600 and identify whether the issue will happen or not? P.S I had actually change the timeout found in `ansible.cfg` and the installation failed too

Timeout error
```
    icp: TASK [Gathering Facts] *********************************************************
    icp: ok: [192.168.27.101]
    icp: ok: [192.168.27.102]
    icp: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 60 seconds
    icp: fatal: [192.168.27.100]: FAILED! => changed=false
    icp:   cmd: /sbin/udevadm info --query property --name /dev/sda1
    icp:   msg: Timer expired after 60 seconds
    icp:   rc: 257
    icp:

```
SSH issue
```
    icp: PLAY RECAP *********************************************************************
    icp: 192.168.27.100             : ok=1    changed=1    unreachable=0    failed=1
    icp: 192.168.27.101             : ok=2    changed=1    unreachable=0    failed=0
    icp: 192.168.27.102             : ok=2    changed=1    unreachable=0    failed=0
    icp: localhost                  : ok=3    changed=3    unreachable=0    failed=0
    icp: Playbook run took 0 days, 0 hours, 5 minutes, 21 seconds
==> icp: Running provisioner: shell...
    icp: Running: script: install_kubectl
    icp:   % Total
    icp:  % Rece
    icp: ived % Xferd
    icp: Average Speed   T
    icp: ime    Tim
    icp: e     Time
    icp:   Current
    icp:
    icp:
    icp:
    icp:       Dloa
    icp: d  Uploa
    icp: d   Total
    icp:    Spent
    icp:  Left  S
    icp: peed
  0   p:
    icp:   0    0
    icp:      0
    icp: 0     0
    icp:     0
    icp:    0 --:-
    icp: -:-- --:--:-- --
    icp: :--:--
    icp:    0
    icp: curl: (
    icp: 7) Fail
    icp: ed to conn
    icp: ect to 1
    icp: 92.168.27.
    icp: 100 port 8443:
    icp:  Connection
    icp:  refused
    icp: chmod: cannot access '/tmp/kubectl': No such file or directory
    icp: mv: cannot stat '/tmp/kubectl': No such file or directory
==> icp: Running provisioner: shell...
    icp: Running: script: install_helm
    icp:
    icp:
    icp: %
    icp:
    icp: T
    icp: o
    icp: t
    icp: a
    icp: l
    icp:
    icp:
    icp:
    icp:
    icp: %
    icp:
    icp: Received % Xferd  Average Speed   Time    Time     Time  Current
    icp:
    icp:
    icp:
    icp:
    icp: Dload
    icp:   Upl
    icp: oa
    icp: d   Tot
    icp: al   Sp
    icp: ent    Le
    icp: ft  Spee
    icp: d
  0  cp:
    icp:    0
    icp:     0
    icp:      0
    icp:    0
    icp: 0      0
    icp:
    icp:  0 --
    icp: :--:-
    icp: - --:--:-- --:--
    icp: :--
    icp: 0
    icp: curl: (7) Failed to connect to 192
    icp: .168.27.
    icp: 100 port
    icp: 8443: Con
    icp: nectio
    icp: n re
    icp: fused
    icp: tar (child):
    icp: /tmp/helm.tar.gz: Cannot open
    icp: : No such file or directory
    icp: tar (child):
    icp: Error is not recoverable: exiting now
    icp: tar: Child returned status 2
    icp: tar: Error is not recoverable: exiting now
    icp: mv: cannot stat '/tmp/linux-amd64/helm': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
