### ISSUE TITLE
Unable to connect to the server: dial tcp 192.168.36.100:8001: connect: no route to host

### ISSUE THREAD

**Issue by Samleo8** [IBM/deploy-ibm-cloud-private#215]
I installed IBM cloud using Vagrant setup as per the docs, but am getting the following error whenever I try to run any `kubectl` commands, for example `kubectl version`:
`Unable to connect to the server: dial tcp 192.168.36.100:8001: connect: no route to host`

**Errors and Outputs:**

1. `$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 192.168.36.100:8001: connect: no route to host
```

This happens regardless of whether Vagrant is up.

Occasionally, I get this error instead:
`The connection to the server 192.168.36.100:8001 was refused - did you specify the right host or port?`

2. `$ sudo docker ps`
Nothing

3. `$ vagrant port`
```
The forwarded ports for the machine are listed below. Please note that
these values may differ from values configured in the Vagrantfile if the
provider supports automatic port collision detection and resolution.
    22 (guest) => 2222 (host)
```

4. `$ kubectl config view`
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.36.100:8001
  name: mycluster.icp
contexts:
- context:
    cluster: mycluster.icp
    namespace: default
    user: mycluster.icp-user
  name: mycluster.icp-context
current-context: mycluster.icp-context
kind: Config
preferences: {}
users:
- name: mycluster.icp-user
  user:
    token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF0X2hhc2giOiJFaGllVkp1T3VtNEVyWVI0d2NjUThBIiwiaXNzIjoiaHR0cHM6Ly9teWNsdXN0ZXIuaWNwOjk0NDMvb2lkYy9lbmRwb2ludC9PUCIsImF1ZCI6ImM2ZDk3NTdmYWY0NmIyNDBkNTJjNDkyMjg0YzQxYmY5IiwiZXhwIjoxNTA5NjgxNjc0LCJpYXQiOjE1MDk2Mzg0NzR9.oLvpbbmJLnxf-ALAMc7vku-EU7ucp1JEixYf6OALkk76oNsVYhVVWKMyfZWU2IMH98ivo1INAU5SRl2w2bQjvwkzMsa3UScu1XR7GFm3XOl4SUWOGFCxfjxaR7n0zEIH0kaLvsrNUIiHl3kE70HuYcNU1MsOwq9u3NfzaDZnHQFu8NFOeGpsI26GlKrqlT_ROz7bsuQ1-M5KOMV4vjKKL6o95d_Ab0Nb7HXn58jXONRQNEQYPCUWVBJQDbyzq-3zWOFUz_ev8YamQgCDOdaU-Gk2MmiInDAPPvExG6vasBQ4fXyWpoeprPtwkCOAb-bEHFdLL4v4fwQK9RfLS4ZyTQ
```

5. `$ vagrant ssh`
SSH into the machine is successful.
Running `$ lxc ls` gives me:
```
+---------+---------+-----------------------+------+------------+-----------+
|  NAME   |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+---------+---------+-----------------------+------+------------+-----------+
| worker1 | RUNNING | 192.168.36.101 (eth0) |      | PERSISTENT | 0         |
|         |         | 172.17.0.1 (docker0)  |      |            |           |
+---------+---------+-----------------------+------+------------+-----------+
| worker2 | RUNNING | 192.168.36.102 (eth0) |      | PERSISTENT | 0         |
|         |         | 172.17.0.1 (docker0)  |      |            |           |
+---------+---------+-----------------------+------+------------+-----------+
```

I cannot, however, access the web console via https://192.168.36.100:8443 as noted it the docs. I have tried the other ports as well.

**Notes:**
In the Vagrantfile, I modified the `base_segment` to be `192.168.36`. Commands `vagrant destroy` and subsequently `vagrant up` were used as per docs.

Running on Ubuntu 18.04, but Vagrant OSes are 16.04
